Back/feat/cap 37 frontend confirm registration
UkrainianItFamily/clmtools pull request #20
Opened 2022-07-14 10:44 UTC by DenisVelykyi

Add frontend-page for verification email and configure it with backend

2022-07-15 04:29 UTC, UkrainianItFamily requested changes

2022-07-15 04:29 UTC, UkrainianItFamily commented on client/src/store/modules/auth/actions.js
> +            await requestService.post(url);
а нашо тут передавати урл?

2022-07-15 04:29 UTC, UkrainianItFamily commented on client/src/store/modules/auth/actions.js
> +
перенос строки зайвий

2022-07-15 04:29 UTC, UkrainianItFamily commented on client/src/views/VerifyEmail.vue
> +            this.url = this.$router.history.current.query.url.split(process.env.VUE_APP_API_URL)[1];
я не розумію для чого тут передається урл

2022-07-15 09:45 UTC, DenisVelykyi commented on client/src/store/modules/auth/actions.js
> +            await requestService.post(url);
Мы у Насти уточняли, и она наглядно расписала схему:
- Юзер регистрируется, ему отправляется письмо с подтверждением ящика http://joxi.ru/LmGY3ezCBq6RgA
- По ссылке в письме открывается страница подтверждения ящика http://joxi.ru/E2pYk1wCvRg4ZA
- На этой странице происходит парсинг параметра url из ссылки http://joxi.ru/eAOZ4YKtvN3vb2 и по нему отправляется запрос на бэк для подтверждения.

2022-07-15 09:46 UTC, DenisVelykyi commented on client/src/views/VerifyEmail.vue
> +            this.url = this.$router.history.current.query.url.split(process.env.VUE_APP_API_URL)[1];
выше уже отписал, тут продублирую:

Мы у Насти уточняли, и она наглядно расписала схему:
- Юзер регистрируется, ему отправляется письмо с подтверждением ящика http://joxi.ru/LmGY3ezCBq6RgA
- По ссылке в письме открывается страница подтверждения ящика http://joxi.ru/E2pYk1wCvRg4ZA
- На этой странице происходит парсинг параметра url из ссылки http://joxi.ru/eAOZ4YKtvN3vb2 и по этому url есть путь, по которому отправляется пост-запрос на бэк для подтверждения.

2022-07-19 08:11 UTC, UkrainianItFamily requested changes

2022-07-19 08:11 UTC, UkrainianItFamily commented on client/src/store/modules/auth/actions.js
> +    async verifyEmail({ commit }, { url }) {
не передавати тут урл

2022-07-19 08:11 UTC, UkrainianItFamily commented on client/src/views/VerifyEmail.vue
> +            url: '/email/verify/',
не передавати тут урл

2022-07-19 09:21 UTC, UkrainianItFamily approved these changes

2022-07-19 09:21 UTC, merged