Front/feat/cap 40/cap 41/cap 44 personal profile
UkrainianItFamily/clmtools pull request #38
Opened 2022-07-22 13:09 UTC by AndreyOleinych

2022-07-22 15:45 UTC, yevhen-turovets-uitf requested changes

2022-07-22 15:45 UTC, yevhen-turovets-uitf commented on client/src/components/profile/EditProfileForm.vue
> +        // },
комменти

2022-07-22 15:45 UTC, yevhen-turovets-uitf commented on client/src/components/profile/EditProfileForm.vue
> +                <BImg v-else src="/img/empty_avatar.jpg" alt="" center></BImg>
може стилем чи у змінну фото це?

2022-07-22 15:45 UTC, yevhen-turovets-uitf commented on client/src/components/profile/EditProfileForm.vue
> +        ],
чому це статика?

2022-07-26 19:40 UTC, yevhen-turovets-uitf requested changes

2022-07-26 19:40 UTC, yevhen-turovets-uitf commented on api/app/Actions/Handbook/CityAction.php
> +        );
не зовсім це гарна запис... багато різного в одну строку

2022-07-26 19:40 UTC, yevhen-turovets-uitf commented on api/app/Actions/Handbook/CityCollectionAction.php
> +        );
не зовсім це гарна запис... багато різного в одну строку

2022-07-26 19:40 UTC, yevhen-turovets-uitf commented on api/app/Actions/Handbook/CityCollectionResponse.php
> +    public function getCity()
немає типу ретерна

2022-07-26 19:40 UTC, yevhen-turovets-uitf commented on api/app/Actions/Handbook/UniversityAction.php
> +        );
вище написав вже про такое

2022-07-26 19:40 UTC, yevhen-turovets-uitf commented on api/app/Actions/Handbook/UniversityCollectionAction.php
> +        );
вище вже написав про таке

2022-07-26 19:40 UTC, yevhen-turovets-uitf commented on api/app/Actions/Handbook/UniversityCollectionResponse.php
> +    public function getUniversity()
тип повернення

2022-07-26 19:40 UTC, yevhen-turovets-uitf commented on api/app/Models/City.php
> +    public function getName(): string
тут може null бути?

2022-07-26 19:40 UTC, yevhen-turovets-uitf commented on api/database/migrations/2022_07_20_152008_add_users_field_for_edit.php
>              $table->date("date_birth")->nullable();
це точно треба тут видаляти?

2022-07-26 19:40 UTC, yevhen-turovets-uitf commented on api/database/migrations/2022_07_20_152008_add_users_field_for_edit.php
> -            $table->dropColumn("last_name");
це точно треба тут видаляти?

2022-07-26 19:40 UTC, yevhen-turovets-uitf commented on api/database/migrations/2022_07_26_150133_create_cities_table.php
> +            $table->text('name');
чому не string?

2022-07-26 19:40 UTC, yevhen-turovets-uitf commented on api/database/migrations/2022_07_26_150133_create_cities_table.php
> +            $table->timestamps();
нашо тут timestamp??

2022-07-26 19:40 UTC, yevhen-turovets-uitf commented on api/database/migrations/2022_07_26_150616_create_universities_table.php
> +            $table->text('name');
чому тут не стрінг?

2022-07-26 19:40 UTC, yevhen-turovets-uitf commented on api/database/migrations/2022_07_26_150616_create_universities_table.php
> +            $table->timestamps();
не потрібні дати зміни і створення тут

2022-07-26 19:40 UTC, yevhen-turovets-uitf commented on client/src/components/profile/EditProfileForm.vue
> +            if (file && file[0]) {
став холть трохи переноси строк

2022-07-26 19:40 UTC, yevhen-turovets-uitf commented on client/src/components/profile/EditProfileForm.vue
> +        ...mapActions('handbook', ['GET_CITIES','GET_UNIVERSITIES']),
чому в верхньому снейк кейс а в нижньому аппер?

2022-07-26 19:40 UTC, yevhen-turovets-uitf commented on client/src/components/profile/EditProfileForm.vue
> +            return day_arr;
це треба проговорити, нагадай на дейлі

2022-07-26 19:40 UTC, yevhen-turovets-uitf commented on client/src/components/profile/EditProfileForm.vue
> +        },
а чьому це в нормалайзері не зробити??

2022-07-27 11:44 UTC, AndreyOleinych commented on api/database/migrations/2022_07_20_152008_add_users_field_for_edit.php
>              $table->date("date_birth")->nullable();
там в двох міграціях last_name додається при migrate падають конфлікти

2022-07-27 14:02 UTC, yevhen-turovets-uitf approved these changes

2022-07-27 14:02 UTC, merged