Back/feat/cap 2 create registration
UkrainianItFamily/clmtools pull request #5
Opened 2022-07-08 12:18 UTC by DmytroYahuza

2022-07-08 13:43 UTC, UkrainianItFamily requested changes

2022-07-08 13:43 UTC, UkrainianItFamily commented on api/app/Actions/Auth/RegisterAction.php
> +        //$this->mailer->to($user)->send(new WelcomeEmail());
коммент і передивись у всіх файлах переноси строк

2022-07-08 13:43 UTC, UkrainianItFamily commented on api/app/Http/Controllers/RegistrationController.php
> +        RegisterHttpRequest $httpRequest,
нашо тут в назва HTTP ??

2022-07-08 13:43 UTC, UkrainianItFamily commented on api/app/Http/Controllers/VerificationController.php
> +        return response()->json(["msg" => "Email verification link sent on your email id"]);
розбити на екшени

2022-07-08 13:51 UTC, DmytroYahuza commented on api/app/Http/Controllers/RegistrationController.php
> +        RegisterHttpRequest $httpRequest,
в RegisterHttpRequest реализована валидация полей. есть еще RegisterRequest - это другой класс
почему именно Http дописано - так было в предыдущем проекте, но названия у них должны быть разные

2022-07-11 06:38 UTC, UkrainianItFamily commented on api/app/Http/Controllers/RegistrationController.php
> +        RegisterHttpRequest $httpRequest,
Я просто не розумію нашо додавати Http у назву..який в цьому інформаційний сенс?

2022-07-12 08:27 UTC, UkrainianItFamily requested changes

2022-07-12 08:27 UTC, UkrainianItFamily commented on api/app/Exceptions/InvalidExpiredUrlProvidedException.php
> +        parent::__construct('Invalid/Expired url provided.', 401, $previous);
не дуже точна помилка, він або інвалід, або вийшов термін...

2022-07-12 08:27 UTC, UkrainianItFamily commented on api/app/Http/Controllers/Api/VerificationController.php
> +            $user_id,
(int) $user_id

2022-07-12 08:27 UTC, UkrainianItFamily commented on api/app/Http/Controllers/Api/VerificationController.php
> +            $request->get('signature')
вони тоді не використовуються

2022-07-12 08:27 UTC, UkrainianItFamily commented on api/app/Http/Controllers/Api/VerificationController.php
> +        return $this->successResponse(['msg' => 'Email verification link sent on your email id']);
Email verification link sent on your email

2022-07-12 08:27 UTC, UkrainianItFamily commented on api/app/Actions/Auth/VerificationRequest.php
> +        private Request $request,
зробит саму змінну з нормальною назвою, не реквест а типа $validSignature - і метод буде getValidSignature

2022-07-12 08:27 UTC, UkrainianItFamily commented on api/routes/api.php
> +    Route::get('email/verify/{id}', [VerificationController::class, 'verify'])->name('verification.verify');
передивитись круд протоколи

2022-07-12 08:27 UTC, UkrainianItFamily commented on api/app/Notifications/EmailVerificationNotification.php
> +
це змінити

2022-07-12 16:57 UTC, UkrainianItFamily approved these changes

2022-07-12 16:57 UTC, merged