Back/feat/cap 64 add lection page
UkrainianItFamily/clmtools pull request #53
Opened 2022-07-28 13:33 UTC by DenisVelykyi

part II
saving lecture

2022-07-28 14:47 UTC, yevhen-turovets-uitf requested changes

2022-07-28 14:47 UTC, yevhen-turovets-uitf commented on api/app/Actions/Auth/AuthRequest.php
> +    public static function getAuthUserId(): int
чому функції статичні?

2022-07-28 14:47 UTC, yevhen-turovets-uitf commented on api/app/Actions/Auth/AuthRequest.php
>  final class AuthRequest
нашо цей реквест як  шо він не передає данні?

2022-07-28 14:47 UTC, yevhen-turovets-uitf commented on api/app/Actions/Lecture/LectureCreateAction.php
> +            'https://via.placeholder.com/600/5F113B/FFFFFF/?text='.$request->getTitle();
в констатни

2022-07-29 06:49 UTC, DenisVelykyi commented on api/app/Actions/Auth/AuthRequest.php
> +    public static function getAuthUserId(): int
щоб зручніше було до них звертатися, не створюючи об'єктів, т.к. там лише гетери значень/станів авторизованого користувача

2022-07-29 06:52 UTC, DenisVelykyi commented on api/app/Actions/Auth/AuthRequest.php
>  final class AuthRequest
Він замислювався як реквест, але за фактом він є проміжним допоміжним класом для отримання значень/станів авторизованого користувача. Можу його перейменувати, але як буде краще?

2022-07-29 08:36 UTC, yevhen-turovets-uitf requested changes

2022-07-29 08:36 UTC, yevhen-turovets-uitf commented on api/app/Actions/Auth/AuthRequest.php
>  final class AuthRequest
Переносишь це в модель - це самий простий варіант.

2022-07-29 08:36 UTC, yevhen-turovets-uitf commented on api/app/Actions/Lecture/LectureCreateAction.php
> +    private const THUMBNAIL_SIZE = '/maxresdefault.jpg';
це ж ще десь буде використовуватися? скоріше да... то перенеси в файли констант...

2022-07-29 14:32 UTC, yevhen-turovets-uitf requested changes

2022-07-29 14:32 UTC, yevhen-turovets-uitf commented on api/app/Models/Authentication.php
> +    }
це в юзера додати, це ж по ньому данні

2022-07-29 14:42 UTC, yevhen-turovets-uitf approved these changes

2022-07-29 14:42 UTC, merged