Back/feat/cap 79 add course page
UkrainianItFamily/clmtools pull request #67
Opened 2022-08-12 09:44 UTC by DenisVelykyi

2022-08-12 11:14 UTC, yevhen-turovets-uitf requested changes

2022-08-12 13:32 UTC, yevhen-turovets-uitf requested changes

2022-08-12 13:32 UTC, yevhen-turovets-uitf commented on api/app/Http/Presenters/CourseArrayPresenter.php
> +            'students' => $this->user_presenter->getCollections($course->getStudents()),
camelCase

2022-08-12 13:32 UTC, yevhen-turovets-uitf commented on api/app/Http/Presenters/CourseArrayPresenter.php
> +                    $response = new CourseResponse($course);
в презентері цього не має бути... тут мають оброблятися данні які ви сюда засунули, а не робитись якась додаткова логіка

2022-08-12 13:32 UTC, yevhen-turovets-uitf commented on api/app/Http/Presenters/LectureArrayPresenter.php
> +            'students' => $this->user_presenter->getCollections($data->getStudents()),
camelCase

2022-08-12 14:10 UTC, DenisVelykyi commented on api/app/Http/Presenters/CourseArrayPresenter.php
> +                    $response = new CourseResponse($course);
Добре, але у нас презентер обробляє лише об'єкти CourseResponse http://joxi.ru/52aGQzMf09llVr, а коли ми розбираємо колекцію Course на окремі елементи моделі Course, то я не можу їх відправити в такому вигляді на обробку, т.к. у нас чітко заданий тип об'єктів CourseResponse на прийом у презентері.

Якщо я перероблю прийом об'єктів у презентері з CourseResponse на простий Course, то в такому випадку буде безучасний CourseResponse з його зверненнями, якщо не призначати його таким же чином у самому методі, що також не є правильним http://joxi.ru/LmGY3ezCZ4BYOA

І що в такому разі краще зробити? Створити якийсь метод у моделі курсу, який при зверненні до нього перетворюватиме об'єкт з Course на CourseResponse http://joxi.ru/5mdlWYECJ4q65m?

2022-08-16 16:06 UTC, yevhen-turovets-uitf requested changes

2022-08-16 16:06 UTC, yevhen-turovets-uitf commented on api/app/Actions/Lecture/LectureFormResponse.php
>  final class LectureFormResponse
чому Form? Взагалі звідки ти взяв шо це якийс FormResponce - чим ця назва пояснюю шо тут за данні?

2022-08-16 16:06 UTC, yevhen-turovets-uitf commented on api/app/Actions/Lecture/LectureShowAction.php
> +final class LectureShowAction
те ж саме писав вище по назві

2022-08-16 16:06 UTC, yevhen-turovets-uitf commented on api/app/Actions/Lecture/LectureShowAction.php
> +            $this->courseRepository->getCoursesByAuthor(User::getAuthUserId())
так само описував нормально розбити

2022-08-16 16:06 UTC, yevhen-turovets-uitf commented on api/app/Actions/User/UserStudentsAction.php
> +final class UserStudentsAction
жаба риба екшен - понятно шо буде робити цей екшен?

2022-08-16 16:06 UTC, yevhen-turovets-uitf commented on api/app/Http/Presenters/LectureArrayPresenter.php
> +        return $this->coursesPresenter->getCollections($data->getCourses());
я ж пояснив шо тут не моде цього бути, шо воно виноситься в контроллер...

2022-08-16 16:06 UTC, yevhen-turovets-uitf commented on api/app/Models/Course.php
> +    }
users() і getStudents() повертають одне і те саме...

2022-08-16 16:06 UTC, yevhen-turovets-uitf commented on api/routes/api.php
> +            Route::post('course', [CourseControllers::class, 'createCourse'])->name('create.course');
все має бути у множині (ну треба прочитати все таки то шо тобі скинув, а не писати з того шо я просто відписав)... 
users
courses
lectures

2022-08-17 14:26 UTC, yevhen-turovets-uitf approved these changes

2022-08-17 14:26 UTC, merged