Front/feat/cap 78 add course page
UkrainianItFamily/clmtools pull request #68
Opened 2022-08-15 13:58 UTC by DenisVelykyi

2022-08-16 07:28 UTC, yevhen-turovets-uitf requested changes

2022-08-16 07:28 UTC, yevhen-turovets-uitf commented on client/src/store/modules/courses/actions.js
> +          });
це переробиться коли ти переробишь той контроллер, тому чекаємо спочатку попередній реквест

2022-08-16 07:28 UTC, yevhen-turovets-uitf commented on client/src/store/modules/courses/actions.js
> +            await ApiRequestService.post('/form-courses', {
як шо ти додаєшь курс, то використовуй нормальну назву роута

2022-08-16 07:28 UTC, yevhen-turovets-uitf commented on client/src/store/modules/courses/actions.js
> +            await ApiRequestService.delete('/delete-course/' + course_id);
Ми пишемо по REST API все... роути мають бути по ньому:
тобто є ресурс курси і для нього мають бути роути:
- GET  /course/ - тримуємо всі курси (або додаєшь параметри якісь там)
- GET /course/{id} - отримуєшь конкретний курс
- POST /course/ - додавання курса
- PUT /course/{id} - оновлення курса
- DELETE /course/{id} - видалення курса

Коротко про рест https://habr.com/ru/post/483202/

2022-08-16 07:28 UTC, yevhen-turovets-uitf commented on client/src/store/modules/courses/types/getters.js
> +export const GET_STUDENTS = 'getStudents';
чого гетери з маленької?

2022-08-16 13:49 UTC, DenisVelykyi commented on client/src/store/modules/courses/types/getters.js
> +export const GET_STUDENTS = 'getStudents';
тому що всі гетери в прикладах були з маленькою
виправив на велику

2022-08-18 09:14 UTC, yevhen-turovets-uitf requested changes

2022-08-18 09:14 UTC, yevhen-turovets-uitf commented on client/src/store/modules/courses/actions.js
> +          dispatch('users/GET_STUDENTS');
а нашо ти тут викликаєшь як шо ніде далі не використовуєшь цей виклик?

2022-08-18 09:44 UTC, DenisVelykyi commented on client/src/store/modules/courses/actions.js
> +          dispatch('users/GET_STUDENTS');
Курсы лектора для страницы курсов.
Студенты - для блока добавления курсов.

Но по факту блоки разные, логичнее разделить их. Разделил.

2022-08-18 10:33 UTC, yevhen-turovets-uitf approved these changes

2022-08-18 10:34 UTC, merged