Сreate authorization test
UkrainianItFamily/clmtools pull request #8
Opened 2022-07-08 14:30 UTC by DenisVelykyi

2022-07-11 06:46 UTC, UkrainianItFamily requested changes

2022-07-11 06:46 UTC, UkrainianItFamily commented on api/tests/Feature/AuthApiTest.php
> +    public function test_existent_user()
в назві помилка орфографічна

2022-07-11 06:46 UTC, UkrainianItFamily commented on api/tests/Feature/AuthApiTest.php
> +        ]);
створи юзера та тестові данні в 
    public function setUp()

2022-07-11 06:46 UTC, UkrainianItFamily commented on api/tests/Feature/AuthApiTest.php
> +            ->assertSeeText('error');
тут краще зробити точково, яку саме неправильну data ти тестуєшь? Наскільки я зрозумів це імейл - то ді по коду правильно шоб поверталась валідаційна помилка а не просто error

2022-07-11 06:46 UTC, UkrainianItFamily commented on api/tests/Feature/AuthApiTest.php
> +            ->assertSeeText('error');
по коду правильно шоб поверталась валідаційна помилка а не просто error

2022-07-11 19:41 UTC, UkrainianItFamily requested changes

2022-07-11 19:41 UTC, UkrainianItFamily commented on api/tests/Feature/AuthApiTest.php
> +        ]);
ти в сетапі маєшь створити користувача і тут вже його використовувати... будь ласка, напиши мені у відповідь в коммент для чого використовується setUp()

2022-07-12 06:10 UTC, DenisVelykyi commented on api/tests/Feature/AuthApiTest.php
> +        ]);
SetUp нужен для инициализации переменных и данных для теста.
Юзера создаю в тесте, т.к. он нужен только в одном тесте, а тестов там всего 4.
Если создание юзера перенести в SetUp, то он будет создаваться при каждом тесте http://joxi.ru/GrqQeXwszX48Rr и 3 из 4 созданных тестовых юзеров будут забивать БД, и придётся добавлять ещё и tearDown, чтобы их "вытирать" каждый раз.

Т.е. правильней будет не использовать в конкретном тесте разовое создание юзера, а делать их всё время и добавлять ещё код на их же удаление?

2022-07-12 09:32 UTC, UkrainianItFamily commented on api/tests/Feature/AuthApiTest.php
> +        ]);
1. Ми для тестів будемо ставити тестову базу - і вона буде затиратися
2. Зроби tear down
3. так краще зробити в одному місті користувача ніж його в кожному тесті потенційно створювати... привчи себе створювати данні для тесту в сетапі

2022-07-12 16:58 UTC, UkrainianItFamily approved these changes

2022-07-12 16:58 UTC, merged