Back/feat/cap 61/cap 67 backend frontend chat with teacher
UkrainianItFamily/clmtools pull request #81
Opened 2022-08-18 12:14 UTC by DmytroYahuza

2022-08-18 15:12 UTC, yevhen-turovets-uitf requested changes

2022-08-18 15:12 UTC, yevhen-turovets-uitf commented on client/src/store/modules/chat/types/getters.js
> +export const POST_CHAT = 'postChat';
чому з маленької букви?

2022-08-18 15:49 UTC, DmytroYahuza commented on client/src/store/modules/chat/types/getters.js
> +export const POST_CHAT = 'postChat';
поменял названия в actions.js на lowerCamelCase. дописал к названиям "Action", т.к. у них должно отличаться название от геттеров

2022-08-19 06:23 UTC, yevhen-turovets-uitf commented on client/src/store/modules/chat/types/getters.js
> +export const POST_CHAT = 'postChat';
виправляй в усіх екшенах і константах vuex

2022-08-19 15:52 UTC, yevhen-turovets-uitf approved these changes

2022-08-19 15:52 UTC, merged