Back/feat/cap 86 edit course
UkrainianItFamily/clmtools pull request #84
Opened 2022-08-19 14:37 UTC by DenisVelykyi

2022-08-19 15:55 UTC, yevhen-turovets-uitf requested changes

2022-08-19 15:55 UTC, yevhen-turovets-uitf commented on api/app/Actions/Course/CourseEditAction.php
> +        $course = $this->courseRepository->getById($request->getId());
а як шо такого курсу немає?

2022-08-19 15:55 UTC, yevhen-turovets-uitf commented on api/app/Repository/UserRepository.php
> +        }
в екшен цю логіку

2022-08-19 16:40 UTC, DenisVelykyi commented on api/app/Actions/Course/CourseEditAction.php
> +        $course = $this->courseRepository->getById($request->getId());
там findOrFail стоїть і віддасть помилку

2022-08-21 11:03 UTC, yevhen-turovets-uitf requested changes

2022-08-21 11:03 UTC, yevhen-turovets-uitf commented on api/app/Actions/Course/CourseEditAction.php
> +        $this->userRepository->setStudentsCourse($old_students_id, null);
не зрозумів цієї логіки

2022-08-22 07:32 UTC, yevhen-turovets-uitf requested changes

2022-08-22 07:32 UTC, yevhen-turovets-uitf commented on api/app/Repository/CourseRepository.php
> +    }
порушен принцип єдиної відповідальності

2022-08-22 07:36 UTC, DenisVelykyi commented on api/app/Repository/CourseRepository.php
> +    }
а чим саме? у цьому методі йде робота тільки зі студентами курсу "$course->users()" і все
перший рядок вичищає всіх, щоб враховувалися видалені з курсу, а другий перепризначає

2022-08-22 08:02 UTC, yevhen-turovets-uitf approved these changes

2022-08-22 08:02 UTC, merged